# This is a workflow that should run daily
name: Daily test (self-hosted, CPU)

# Controls when the action will run.
on:
  schedule:
    - cron: '00 19 * * *'  # run at 19:00 UTC daily

# This workflow calls the test_gpu.yaml workflow passing the default
# branches as inputs. The cron workflow will not run on forks.
jobs:
  run-tests-cron-sh-cpu:
    if: github.repository == 'xsuite/xsuite'
    uses: ./.github/workflows/test_sh.yaml
    with:
      xobjects_location: 'xsuite:main'
      xdeps_location: 'xsuite:main'
      xpart_location: 'xsuite:main'
      xtrack_location: 'xsuite:main'
      xfields_location: 'xsuite:main'
      xmask_location: 'xsuite:main'
      xcoll_location: 'xsuite:main'
      test_contexts: 'ContextCpu;ContextCpu:auto'
      platform: 'alma-cpu'
      suites: '["xobjects", "xdeps", "xpart", "xtrack", "xfields", "xmask", "xcoll"]'
